# Generated by Django 2.0 on 2019-04-21 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='It',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('course_of_study', models.CharField(max_length=60)),
                ('Faculty', models.CharField(max_length=50)),
                ('Level', models.CharField(max_length=12)),
                ('name_of_the_company', models.CharField(max_length=500)),
                ('address_of_the_company', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=200)),
                ('name_of_industry_based_supervisor', models.CharField(max_length=500)),
                ('address_of_industry_based_supervisor', models.CharField(max_length=500)),
                ('Matriculation_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Matriculation_Number', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=60)),
                ('Faculty', models.CharField(max_length=50)),
                ('Level', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
