# Generated by Django 2.0 on 2019-04-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it',
            name='Matriculation_Number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
